function t = patient_table
  
  %% Gender, Location, SelfAssessedHealthStatus
  load patients;   %#ok<LOAD>
  Gender = categorical(Gender, 'Protected', true); %#ok<NODEF>  
  SelfAssessedHealthStatus = categorical(SelfAssessedHealthStatus, ...
                                         {'Poor' ...
                                          'Fair' ...
                                          'Good' ...
                                          'Excellent'}, ...
                                        'Ordinal', true); %#ok<NODEF>
  Location = categorical(Location, 'Protected', true); %#ok<NODEF>
  %% Body Mass Index
  BMI = Weight./Height.^2*703;
  BMI_Class = categorical(repmat({''}, size(BMI)), ...
                         {'Underweight' ...
                          'Healthy' ...
                          'Overweight' ...
                          'Obese'}, ...
                          'Ordinal', true);
  BMI_Class(BMI < 18.5) = 'Underweight';
  BMI_Class(18.5 <= BMI & BMI <= 24.9) = 'Healthy';
  BMI_Class(25 <= BMI & BMI <= 29.9) = 'Overweight';
  BMI_Class(BMI >= 30) = 'Obese';
  %% Blood Pressure
  BloodPressure_Class = categorical(repmat({''}, size(Systolic)), ...
                                   {'Low', ...
                                    'Normal', ...
                                    'Prehypertension', ...
                                    'Hypertension'}, ...
                                    'Ordinal', true);
  BloodPressure_Class((Systolic < 80) | (Diastolic < 60)) = 'Low';
  BloodPressure_Class((80 <= Systolic & Systolic <= 120) & ...
                      (60 <= Diastolic & Diastolic <= 80)) = 'Normal';
  BloodPressure_Class((121 <= Systolic & Systolic <= 139) | ...
                      (80 <= Diastolic & Diastolic <= 89)) = 'Prehypertension';
  BloodPressure_Class((140 <= Systolic & Systolic <= 159) | ...
                      (90 <= Diastolic & Diastolic <= 99)) = 'Hypertension';
  %% table
  t = table(Age, Gender, Smoker, Weight, Height, ...
            BMI, BMI_Class, Systolic, Diastolic, BloodPressure_Class, ...
            SelfAssessedHealthStatus, Location, 'RowNames', LastName);
